name: Fuzz

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Create corpus directories
        run: mkdir -p fuzz/corpus/{roundtrip,roundtrip_zlib,decode_buffer}
      - name: Fuzz roundtrip
        run: cargo +nightly fuzz run --fuzz-dir fuzz roundtrip fuzz/corpus/roundtrip -j2 -- -timeout=10s -max_total_time=120
      - name: Fuzz roundtrip_zlib
        run: cargo +nightly fuzz run --fuzz-dir fuzz roundtrip_zlib fuzz/corpus/roundtrip_zlib -j2 -- -timeout=10s -max_total_time=120
      - name: Fuzz decode_buffer
        run: cargo +nightly fuzz run --fuzz-dir fuzz decode_buffer fuzz/corpus/decode_buffer -j2 -- -timeout=10s -max_total_time=120
      - name: Fuzz decode_zlib
        run: cargo +nightly fuzz run --fuzz-dir fuzz decode_zlib -j2 -- -timeout=10s -max_total_time=120
